# Clock and Reset
set_property PACKAGE_PIN W5 [get_ports clkin]
set_property IOSTANDARD LVCMOS33 [get_ports clkin]
set_property PACKAGE_PIN T18 [get_ports rst]
set_property IOSTANDARD LVCMOS33 [get_ports rst]

# Control Inputs
set_property PACKAGE_PIN U18 [get_ports startMult]
set_property IOSTANDARD LVCMOS33 [get_ports startMult]
set_property PACKAGE_PIN W19 [get_ports scrLeft]
set_property IOSTANDARD LVCMOS33 [get_ports scrLeft]
set_property PACKAGE_PIN T17 [get_ports scrRight]
set_property IOSTANDARD LVCMOS33 [get_ports scrRight]

# Input X[7:0]
set_property PACKAGE_PIN R2 [get_ports {X[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {X[7]}]
set_property PACKAGE_PIN T1 [get_ports {X[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {X[6]}]
set_property PACKAGE_PIN U1 [get_ports {X[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {X[5]}]
set_property PACKAGE_PIN W2 [get_ports {X[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {X[4]}]
set_property PACKAGE_PIN R3 [get_ports {X[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {X[3]}]
set_property PACKAGE_PIN T2 [get_ports {X[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {X[2]}]
set_property PACKAGE_PIN T3 [get_ports {X[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {X[1]}]
set_property PACKAGE_PIN V2 [get_ports {X[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {X[0]}]

# Input Y[7:0]
set_property PACKAGE_PIN W13 [get_ports {Y[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {Y[7]}]
set_property PACKAGE_PIN W14 [get_ports {Y[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {Y[6]}]
set_property PACKAGE_PIN V15 [get_ports {Y[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {Y[5]}]
set_property PACKAGE_PIN W15 [get_ports {Y[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {Y[4]}]
set_property PACKAGE_PIN W17 [get_ports {Y[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {Y[3]}]
set_property PACKAGE_PIN W16 [get_ports {Y[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {Y[2]}]
set_property PACKAGE_PIN V16 [get_ports {Y[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {Y[1]}]
set_property PACKAGE_PIN V17 [get_ports {Y[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {Y[0]}]

# Output fullprod[15:0]
#set_property PACKAGE_PIN U16 [get_ports {fullprod[0]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {fullprod[0]}]
#set_property PACKAGE_PIN E19 [get_ports {fullprod[1]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {fullprod[1]}]
#set_property PACKAGE_PIN U19 [get_ports {fullprod[2]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {fullprod[2]}]
#set_property PACKAGE_PIN V19 [get_ports {fullprod[3]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {fullprod[3]}]
#set_property PACKAGE_PIN W18 [get_ports {fullprod[4]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {fullprod[4]}]
#set_property PACKAGE_PIN U15 [get_ports {fullprod[5]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {fullprod[5]}]
#set_property PACKAGE_PIN U14 [get_ports {fullprod[6]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {fullprod[6]}]
#set_property PACKAGE_PIN V14 [get_ports {fullprod[7]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {fullprod[7]}]
#set_property PACKAGE_PIN V13 [get_ports {fullprod[8]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {fullprod[8]}]
#set_property PACKAGE_PIN V3 [get_ports {fullprod[9]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {fullprod[9]}]
#set_property PACKAGE_PIN W3 [get_ports {fullprod[10]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {fullprod[10]}]
#set_property PACKAGE_PIN U3 [get_ports {fullprod[11]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {fullprod[11]}]
#set_property PACKAGE_PIN P3 [get_ports {fullprod[12]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {fullprod[12]}]
#set_property PACKAGE_PIN N3 [get_ports {fullprod[13]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {fullprod[13]}]
#set_property PACKAGE_PIN P1 [get_ports {fullprod[14]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {fullprod[14]}]
#set_property PACKAGE_PIN L1 [get_ports {fullprod[15]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {fullprod[15]}]

# Output 7-segment segments_a_to_g[6:0]
set_property PACKAGE_PIN W7 [get_ports {segments_a_to_g[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {segments_a_to_g[6]}]
set_property PACKAGE_PIN W6 [get_ports {segments_a_to_g[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {segments_a_to_g[5]}]
set_property PACKAGE_PIN U8 [get_ports {segments_a_to_g[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {segments_a_to_g[4]}]
set_property PACKAGE_PIN V8 [get_ports {segments_a_to_g[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {segments_a_to_g[3]}]
set_property PACKAGE_PIN U5 [get_ports {segments_a_to_g[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {segments_a_to_g[2]}]
set_property PACKAGE_PIN V5 [get_ports {segments_a_to_g[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {segments_a_to_g[1]}]
set_property PACKAGE_PIN U7 [get_ports {segments_a_to_g[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {segments_a_to_g[0]}]

# Output finanode[3:0]
set_property PACKAGE_PIN W4 [get_ports {finanode[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {finanode[3]}]
set_property PACKAGE_PIN V4 [get_ports {finanode[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {finanode[2]}]
set_property PACKAGE_PIN U4 [get_ports {finanode[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {finanode[1]}]
set_property PACKAGE_PIN U2 [get_ports {finanode[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {finanode[0]}]
